### ISSUE TITLE
เอา `shit` ออกจากชื่อ project

### ISSUE THREAD

**Issue by lion328** [nutterrocker/callback-shit#1]
สวัสดีครับ พอดี follow พี่นัทไว้แล้วเห็นคำว่า `shit` ผมรับไม่ได้ครับ ขอความกรุณาลบออกด้วยครับ

ปล. หัวร้อนมาหรือเปล่าครับ

**Comment by nutterrocker** [comment]
We will consider your issue and will respond ASAP. 
By the way, my sincere appreciation for your snooping. 😃
